/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.perfil;

/**
 *
 * @author dizan
 */
public class EncuestaEficaciaVista extends javax.swing.JDialog {

    /**
     * Creates new form EncuestaEficaciaVista
     */
    public EncuestaEficaciaVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelCurso = new javax.swing.JLabel();
        panelDatosCurso = new javax.swing.JPanel();
        labelInstrucciones = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        botonAcuerdo1 = new javax.swing.JButton();
        botonAcuerdo2 = new javax.swing.JButton();
        botonAcuerdo3 = new javax.swing.JButton();
        botonAcuerdo4 = new javax.swing.JButton();
        botonAcuerdo5 = new javax.swing.JButton();
        panelRespuestas = new javax.swing.JPanel();
        labelRespuesta = new javax.swing.JLabel();
        panelRespuesta1 = new javax.swing.JPanel();
        panelAfirmacion1 = new javax.swing.JPanel();
        labelAfirmacion1 = new javax.swing.JLabel();
        panelRespuestaAfirmacion1 = new javax.swing.JPanel();
        radio1A1 = new javax.swing.JRadioButton();
        radio2A1 = new javax.swing.JRadioButton();
        radio3A1 = new javax.swing.JRadioButton();
        radio4A1 = new javax.swing.JRadioButton();
        radio5A1 = new javax.swing.JRadioButton();
        panelRespuesta2 = new javax.swing.JPanel();
        panelAfirmacion2 = new javax.swing.JPanel();
        labelAfirmacion2 = new javax.swing.JLabel();
        panelRespuestaAfirmacion2 = new javax.swing.JPanel();
        radio1A2 = new javax.swing.JRadioButton();
        radio2A2 = new javax.swing.JRadioButton();
        radio3A2 = new javax.swing.JRadioButton();
        radio4A2 = new javax.swing.JRadioButton();
        radio5A2 = new javax.swing.JRadioButton();
        panelRespuesta3 = new javax.swing.JPanel();
        panelAfirmacion3 = new javax.swing.JPanel();
        labelAfirmacion3 = new javax.swing.JLabel();
        panelRespuestaAfirmacion3 = new javax.swing.JPanel();
        radio1A3 = new javax.swing.JRadioButton();
        radio2A3 = new javax.swing.JRadioButton();
        radio3A3 = new javax.swing.JRadioButton();
        radio4A3 = new javax.swing.JRadioButton();
        radio5A3 = new javax.swing.JRadioButton();
        panelRespuesta4 = new javax.swing.JPanel();
        panelAfirmacion4 = new javax.swing.JPanel();
        labelAfirmacion4 = new javax.swing.JLabel();
        panelRespuestaAfirmacion4 = new javax.swing.JPanel();
        radio1A4 = new javax.swing.JRadioButton();
        radio2A4 = new javax.swing.JRadioButton();
        radio3A4 = new javax.swing.JRadioButton();
        radio4A4 = new javax.swing.JRadioButton();
        radio5A4 = new javax.swing.JRadioButton();
        panelRespuesta5 = new javax.swing.JPanel();
        panelAfirmacion5 = new javax.swing.JPanel();
        labelAfirmacion5 = new javax.swing.JLabel();
        panelRespuestaAfirmacion5 = new javax.swing.JPanel();
        radio1A5 = new javax.swing.JRadioButton();
        radio2A5 = new javax.swing.JRadioButton();
        radio3A5 = new javax.swing.JRadioButton();
        radio4A5 = new javax.swing.JRadioButton();
        radio5A5 = new javax.swing.JRadioButton();
        panelRespuesta6 = new javax.swing.JPanel();
        panelAfirmacion6 = new javax.swing.JPanel();
        labelAfirmacion6 = new javax.swing.JLabel();
        panelRespuestaAfirmacion6 = new javax.swing.JPanel();
        radio1A6 = new javax.swing.JRadioButton();
        radio2A6 = new javax.swing.JRadioButton();
        radio3A6 = new javax.swing.JRadioButton();
        radio4A6 = new javax.swing.JRadioButton();
        radio5A6 = new javax.swing.JRadioButton();
        panelRespuesta7 = new javax.swing.JPanel();
        panelAfirmacion7 = new javax.swing.JPanel();
        labelAfirmacion7 = new javax.swing.JLabel();
        panelRespuestaAfirmacion7 = new javax.swing.JPanel();
        radio1A7 = new javax.swing.JRadioButton();
        radio2A7 = new javax.swing.JRadioButton();
        radio3A7 = new javax.swing.JRadioButton();
        radio4A7 = new javax.swing.JRadioButton();
        radio5A7 = new javax.swing.JRadioButton();
        panelRespuesta8 = new javax.swing.JPanel();
        panelAfirmacion8 = new javax.swing.JPanel();
        labelAfirmacion8 = new javax.swing.JLabel();
        panelRespuestaAfirmacion8 = new javax.swing.JPanel();
        radio1A8 = new javax.swing.JRadioButton();
        radio2A8 = new javax.swing.JRadioButton();
        radio3A8 = new javax.swing.JRadioButton();
        radio4A8 = new javax.swing.JRadioButton();
        radio5A8 = new javax.swing.JRadioButton();
        panelSugerencia = new javax.swing.JPanel();
        jScrollPaneSugerencia = new javax.swing.JScrollPane();
        jTextPaneSugerencia = new javax.swing.JTextPane();
        panelBoton = new javax.swing.JPanel();
        botonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Encuesta de eficacia");
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelPrincipal.setBackground(new java.awt.Color(0, 78, 97));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelTitulo.setBackground(new java.awt.Color(0, 78, 97));
        panelTitulo.setLayout(new java.awt.GridBagLayout());

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Encuesta de eficacia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelTitulo.add(labelTitulo, gridBagConstraints);

        labelCurso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCurso.setForeground(new java.awt.Color(255, 255, 255));
        labelCurso.setText("Curso: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelTitulo.add(labelCurso, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelTitulo, gridBagConstraints);

        panelDatosCurso.setBackground(new java.awt.Color(0, 78, 97));

        labelInstrucciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        labelInstrucciones.setText("<html><body>Considerando la necesidad de evaluar los cursos a los cuales Usted asistió, se le solicita conteste las siguientes preguntas, marcando con una X la respuesta que a su juicio corresponda a la afirmación realizada, partiendo de la siguiente escala</body></html>");

        javax.swing.GroupLayout panelDatosCursoLayout = new javax.swing.GroupLayout(panelDatosCurso);
        panelDatosCurso.setLayout(panelDatosCursoLayout);
        panelDatosCursoLayout.setHorizontalGroup(
            panelDatosCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelDatosCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosCursoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelInstrucciones)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelDatosCursoLayout.setVerticalGroup(
            panelDatosCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelDatosCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosCursoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelInstrucciones)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelPrincipal.add(panelDatosCurso, gridBagConstraints);

        panelOpciones.setBackground(new java.awt.Color(0, 78, 97));
        panelOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelOpciones.setLayout(new java.awt.GridBagLayout());

        botonAcuerdo1.setText("<html><body>1.- Totalmente de acuerdo</body><html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelOpciones.add(botonAcuerdo1, gridBagConstraints);

        botonAcuerdo2.setText("<html><body>2.- Parcialmente en desacuerdo</body></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelOpciones.add(botonAcuerdo2, gridBagConstraints);

        botonAcuerdo3.setText("<html><body>3.- Indiferente</body></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelOpciones.add(botonAcuerdo3, gridBagConstraints);

        botonAcuerdo4.setText("<html><body>4.- Parcialmente de acuerdo</body></html>");
        botonAcuerdo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcuerdo4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelOpciones.add(botonAcuerdo4, gridBagConstraints);

        botonAcuerdo5.setText("<html><body>5.- Totalmente de acuerdo</body></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelOpciones.add(botonAcuerdo5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelPrincipal.add(panelOpciones, gridBagConstraints);

        panelRespuestas.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuestas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelRespuestas.setForeground(new java.awt.Color(255, 255, 255));
        panelRespuestas.setLayout(new java.awt.GridBagLayout());

        labelRespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        labelRespuesta.setText("Los cursos en los que participó le: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        panelRespuestas.add(labelRespuesta, gridBagConstraints);

        panelRespuesta1.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuesta1.setLayout(new java.awt.GridBagLayout());

        panelAfirmacion1.setBackground(new java.awt.Color(0, 78, 97));
        panelAfirmacion1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAfirmacion1.setLayout(new java.awt.GridLayout(1, 0));

        labelAfirmacion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAfirmacion1.setForeground(new java.awt.Color(255, 255, 255));
        labelAfirmacion1.setText("Produjeron un incremento en su motivación ");
        panelAfirmacion1.add(labelAfirmacion1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelRespuesta1.add(panelAfirmacion1, gridBagConstraints);

        panelRespuestaAfirmacion1.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuestaAfirmacion1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRespuestaAfirmacion1.setLayout(new java.awt.GridBagLayout());

        radio1A1.setBackground(new java.awt.Color(0, 78, 97));
        radio1A1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio1A1.setForeground(new java.awt.Color(255, 255, 255));
        radio1A1.setText("1");
        radio1A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1A1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion1.add(radio1A1, gridBagConstraints);

        radio2A1.setBackground(new java.awt.Color(0, 78, 97));
        radio2A1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio2A1.setForeground(new java.awt.Color(255, 255, 255));
        radio2A1.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion1.add(radio2A1, gridBagConstraints);

        radio3A1.setBackground(new java.awt.Color(0, 78, 97));
        radio3A1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio3A1.setForeground(new java.awt.Color(255, 255, 255));
        radio3A1.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion1.add(radio3A1, gridBagConstraints);

        radio4A1.setBackground(new java.awt.Color(0, 78, 97));
        radio4A1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio4A1.setForeground(new java.awt.Color(255, 255, 255));
        radio4A1.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion1.add(radio4A1, gridBagConstraints);

        radio5A1.setBackground(new java.awt.Color(0, 78, 97));
        radio5A1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio5A1.setForeground(new java.awt.Color(255, 255, 255));
        radio5A1.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion1.add(radio5A1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuesta1.add(panelRespuestaAfirmacion1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelRespuestas.add(panelRespuesta1, gridBagConstraints);

        panelRespuesta2.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuesta2.setLayout(new java.awt.GridBagLayout());

        panelAfirmacion2.setBackground(new java.awt.Color(0, 78, 97));
        panelAfirmacion2.setLayout(new java.awt.GridLayout(1, 0));

        labelAfirmacion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAfirmacion2.setForeground(new java.awt.Color(255, 255, 255));
        labelAfirmacion2.setText("Han servido para su desarrollo personal ");
        labelAfirmacion2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAfirmacion2.add(labelAfirmacion2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelRespuesta2.add(panelAfirmacion2, gridBagConstraints);

        panelRespuestaAfirmacion2.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuestaAfirmacion2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRespuestaAfirmacion2.setLayout(new java.awt.GridBagLayout());

        radio1A2.setBackground(new java.awt.Color(0, 78, 97));
        radio1A2.setForeground(new java.awt.Color(255, 255, 255));
        radio1A2.setText("1");
        radio1A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1A2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion2.add(radio1A2, gridBagConstraints);

        radio2A2.setBackground(new java.awt.Color(0, 78, 97));
        radio2A2.setForeground(new java.awt.Color(255, 255, 255));
        radio2A2.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion2.add(radio2A2, gridBagConstraints);

        radio3A2.setBackground(new java.awt.Color(0, 78, 97));
        radio3A2.setForeground(new java.awt.Color(255, 255, 255));
        radio3A2.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion2.add(radio3A2, gridBagConstraints);

        radio4A2.setBackground(new java.awt.Color(0, 78, 97));
        radio4A2.setForeground(new java.awt.Color(255, 255, 255));
        radio4A2.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion2.add(radio4A2, gridBagConstraints);

        radio5A2.setBackground(new java.awt.Color(0, 78, 97));
        radio5A2.setForeground(new java.awt.Color(255, 255, 255));
        radio5A2.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion2.add(radio5A2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuesta2.add(panelRespuestaAfirmacion2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelRespuestas.add(panelRespuesta2, gridBagConstraints);

        panelRespuesta3.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuesta3.setLayout(new java.awt.GridBagLayout());

        panelAfirmacion3.setBackground(new java.awt.Color(0, 78, 97));
        panelAfirmacion3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAfirmacion3.setLayout(new java.awt.GridLayout(1, 0));

        labelAfirmacion3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAfirmacion3.setForeground(new java.awt.Color(255, 255, 255));
        labelAfirmacion3.setText("Proporcionaron elementos para su desarrollo laboral");
        panelAfirmacion3.add(labelAfirmacion3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelRespuesta3.add(panelAfirmacion3, gridBagConstraints);

        panelRespuestaAfirmacion3.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuestaAfirmacion3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRespuestaAfirmacion3.setLayout(new java.awt.GridBagLayout());

        radio1A3.setBackground(new java.awt.Color(0, 78, 97));
        radio1A3.setForeground(new java.awt.Color(255, 255, 255));
        radio1A3.setText("1");
        radio1A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1A3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion3.add(radio1A3, gridBagConstraints);

        radio2A3.setBackground(new java.awt.Color(0, 78, 97));
        radio2A3.setForeground(new java.awt.Color(255, 255, 255));
        radio2A3.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion3.add(radio2A3, gridBagConstraints);

        radio3A3.setBackground(new java.awt.Color(0, 78, 97));
        radio3A3.setForeground(new java.awt.Color(255, 255, 255));
        radio3A3.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion3.add(radio3A3, gridBagConstraints);

        radio4A3.setBackground(new java.awt.Color(0, 78, 97));
        radio4A3.setForeground(new java.awt.Color(255, 255, 255));
        radio4A3.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion3.add(radio4A3, gridBagConstraints);

        radio5A3.setBackground(new java.awt.Color(0, 78, 97));
        radio5A3.setForeground(new java.awt.Color(255, 255, 255));
        radio5A3.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion3.add(radio5A3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuesta3.add(panelRespuestaAfirmacion3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelRespuestas.add(panelRespuesta3, gridBagConstraints);

        panelRespuesta4.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuesta4.setLayout(new java.awt.GridBagLayout());

        panelAfirmacion4.setBackground(new java.awt.Color(0, 78, 97));
        panelAfirmacion4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAfirmacion4.setLayout(new java.awt.GridLayout(1, 0));

        labelAfirmacion4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAfirmacion4.setForeground(new java.awt.Color(255, 255, 255));
        labelAfirmacion4.setText("Sirvieron para integrarse mejor con sus compañeros de trabajo ");
        panelAfirmacion4.add(labelAfirmacion4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelRespuesta4.add(panelAfirmacion4, gridBagConstraints);

        panelRespuestaAfirmacion4.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuestaAfirmacion4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRespuestaAfirmacion4.setLayout(new java.awt.GridBagLayout());

        radio1A4.setBackground(new java.awt.Color(0, 78, 97));
        radio1A4.setForeground(new java.awt.Color(255, 255, 255));
        radio1A4.setText("1");
        radio1A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1A4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion4.add(radio1A4, gridBagConstraints);

        radio2A4.setBackground(new java.awt.Color(0, 78, 97));
        radio2A4.setForeground(new java.awt.Color(255, 255, 255));
        radio2A4.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion4.add(radio2A4, gridBagConstraints);

        radio3A4.setBackground(new java.awt.Color(0, 78, 97));
        radio3A4.setForeground(new java.awt.Color(255, 255, 255));
        radio3A4.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion4.add(radio3A4, gridBagConstraints);

        radio4A4.setBackground(new java.awt.Color(0, 78, 97));
        radio4A4.setForeground(new java.awt.Color(255, 255, 255));
        radio4A4.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion4.add(radio4A4, gridBagConstraints);

        radio5A4.setBackground(new java.awt.Color(0, 78, 97));
        radio5A4.setForeground(new java.awt.Color(255, 255, 255));
        radio5A4.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion4.add(radio5A4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuesta4.add(panelRespuestaAfirmacion4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelRespuestas.add(panelRespuesta4, gridBagConstraints);

        panelRespuesta5.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuesta5.setLayout(new java.awt.GridBagLayout());

        panelAfirmacion5.setBackground(new java.awt.Color(0, 78, 97));
        panelAfirmacion5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAfirmacion5.setLayout(new java.awt.GridLayout(1, 0));

        labelAfirmacion5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAfirmacion5.setForeground(new java.awt.Color(255, 255, 255));
        labelAfirmacion5.setText("Permitieron una mayor compresión del servicio que presta el Instituto Tecnológico");
        panelAfirmacion5.add(labelAfirmacion5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelRespuesta5.add(panelAfirmacion5, gridBagConstraints);

        panelRespuestaAfirmacion5.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuestaAfirmacion5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRespuestaAfirmacion5.setLayout(new java.awt.GridBagLayout());

        radio1A5.setBackground(new java.awt.Color(0, 78, 97));
        radio1A5.setForeground(new java.awt.Color(255, 255, 255));
        radio1A5.setText("1");
        radio1A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1A5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion5.add(radio1A5, gridBagConstraints);

        radio2A5.setBackground(new java.awt.Color(0, 78, 97));
        radio2A5.setForeground(new java.awt.Color(255, 255, 255));
        radio2A5.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion5.add(radio2A5, gridBagConstraints);

        radio3A5.setBackground(new java.awt.Color(0, 78, 97));
        radio3A5.setForeground(new java.awt.Color(255, 255, 255));
        radio3A5.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion5.add(radio3A5, gridBagConstraints);

        radio4A5.setBackground(new java.awt.Color(0, 78, 97));
        radio4A5.setForeground(new java.awt.Color(255, 255, 255));
        radio4A5.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion5.add(radio4A5, gridBagConstraints);

        radio5A5.setBackground(new java.awt.Color(0, 78, 97));
        radio5A5.setForeground(new java.awt.Color(255, 255, 255));
        radio5A5.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion5.add(radio5A5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuesta5.add(panelRespuestaAfirmacion5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelRespuestas.add(panelRespuesta5, gridBagConstraints);

        panelRespuesta6.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuesta6.setLayout(new java.awt.GridBagLayout());

        panelAfirmacion6.setBackground(new java.awt.Color(0, 78, 97));
        panelAfirmacion6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAfirmacion6.setLayout(new java.awt.GridLayout(1, 0));

        labelAfirmacion6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAfirmacion6.setForeground(new java.awt.Color(255, 255, 255));
        labelAfirmacion6.setText("Permitieron desarrollar habilidades adicionales");
        panelAfirmacion6.add(labelAfirmacion6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelRespuesta6.add(panelAfirmacion6, gridBagConstraints);

        panelRespuestaAfirmacion6.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuestaAfirmacion6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRespuestaAfirmacion6.setLayout(new java.awt.GridBagLayout());

        radio1A6.setBackground(new java.awt.Color(0, 78, 97));
        radio1A6.setForeground(new java.awt.Color(255, 255, 255));
        radio1A6.setText("1");
        radio1A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1A6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion6.add(radio1A6, gridBagConstraints);

        radio2A6.setBackground(new java.awt.Color(0, 78, 97));
        radio2A6.setForeground(new java.awt.Color(255, 255, 255));
        radio2A6.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion6.add(radio2A6, gridBagConstraints);

        radio3A6.setBackground(new java.awt.Color(0, 78, 97));
        radio3A6.setForeground(new java.awt.Color(255, 255, 255));
        radio3A6.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion6.add(radio3A6, gridBagConstraints);

        radio4A6.setBackground(new java.awt.Color(0, 78, 97));
        radio4A6.setForeground(new java.awt.Color(255, 255, 255));
        radio4A6.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion6.add(radio4A6, gridBagConstraints);

        radio5A6.setBackground(new java.awt.Color(0, 78, 97));
        radio5A6.setForeground(new java.awt.Color(255, 255, 255));
        radio5A6.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion6.add(radio5A6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuesta6.add(panelRespuestaAfirmacion6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelRespuestas.add(panelRespuesta6, gridBagConstraints);

        panelRespuesta7.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuesta7.setLayout(new java.awt.GridBagLayout());

        panelAfirmacion7.setBackground(new java.awt.Color(0, 78, 97));
        panelAfirmacion7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAfirmacion7.setLayout(new java.awt.GridLayout(1, 0));

        labelAfirmacion7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAfirmacion7.setForeground(new java.awt.Color(255, 255, 255));
        labelAfirmacion7.setText("<html><body>Generaron un mayor dominio de los conceptos académicos aplicables en la materia que imparte</body></html>");
        panelAfirmacion7.add(labelAfirmacion7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelRespuesta7.add(panelAfirmacion7, gridBagConstraints);

        panelRespuestaAfirmacion7.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuestaAfirmacion7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRespuestaAfirmacion7.setLayout(new java.awt.GridBagLayout());

        radio1A7.setBackground(new java.awt.Color(0, 78, 97));
        radio1A7.setForeground(new java.awt.Color(255, 255, 255));
        radio1A7.setText("1");
        radio1A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1A7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion7.add(radio1A7, gridBagConstraints);

        radio2A7.setBackground(new java.awt.Color(0, 78, 97));
        radio2A7.setForeground(new java.awt.Color(255, 255, 255));
        radio2A7.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion7.add(radio2A7, gridBagConstraints);

        radio3A7.setBackground(new java.awt.Color(0, 78, 97));
        radio3A7.setForeground(new java.awt.Color(255, 255, 255));
        radio3A7.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion7.add(radio3A7, gridBagConstraints);

        radio4A7.setBackground(new java.awt.Color(0, 78, 97));
        radio4A7.setForeground(new java.awt.Color(255, 255, 255));
        radio4A7.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion7.add(radio4A7, gridBagConstraints);

        radio5A7.setBackground(new java.awt.Color(0, 78, 97));
        radio5A7.setForeground(new java.awt.Color(255, 255, 255));
        radio5A7.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion7.add(radio5A7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuesta7.add(panelRespuestaAfirmacion7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelRespuestas.add(panelRespuesta7, gridBagConstraints);

        panelRespuesta8.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuesta8.setLayout(new java.awt.GridBagLayout());

        panelAfirmacion8.setBackground(new java.awt.Color(0, 78, 97));
        panelAfirmacion8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAfirmacion8.setLayout(new java.awt.GridLayout(1, 0));

        labelAfirmacion8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAfirmacion8.setForeground(new java.awt.Color(255, 255, 255));
        labelAfirmacion8.setText("Ayudaron a desarrollar valores compatibles con los suyos");
        panelAfirmacion8.add(labelAfirmacion8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelRespuesta8.add(panelAfirmacion8, gridBagConstraints);

        panelRespuestaAfirmacion8.setBackground(new java.awt.Color(0, 78, 97));
        panelRespuestaAfirmacion8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRespuestaAfirmacion8.setLayout(new java.awt.GridBagLayout());

        radio1A8.setBackground(new java.awt.Color(0, 78, 97));
        radio1A8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio1A8.setForeground(new java.awt.Color(255, 255, 255));
        radio1A8.setText("1");
        radio1A8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1A8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion8.add(radio1A8, gridBagConstraints);

        radio2A8.setBackground(new java.awt.Color(0, 78, 97));
        radio2A8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio2A8.setForeground(new java.awt.Color(255, 255, 255));
        radio2A8.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion8.add(radio2A8, gridBagConstraints);

        radio3A8.setBackground(new java.awt.Color(0, 78, 97));
        radio3A8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio3A8.setForeground(new java.awt.Color(255, 255, 255));
        radio3A8.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion8.add(radio3A8, gridBagConstraints);

        radio4A8.setBackground(new java.awt.Color(0, 78, 97));
        radio4A8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio4A8.setForeground(new java.awt.Color(255, 255, 255));
        radio4A8.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion8.add(radio4A8, gridBagConstraints);

        radio5A8.setBackground(new java.awt.Color(0, 78, 97));
        radio5A8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio5A8.setForeground(new java.awt.Color(255, 255, 255));
        radio5A8.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuestaAfirmacion8.add(radio5A8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelRespuesta8.add(panelRespuestaAfirmacion8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelRespuestas.add(panelRespuesta8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelPrincipal.add(panelRespuestas, gridBagConstraints);

        panelSugerencia.setBackground(new java.awt.Color(0, 78, 97));
        panelSugerencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelSugerencia.setForeground(new java.awt.Color(255, 255, 255));
        panelSugerencia.setLayout(new java.awt.GridLayout());

        jTextPaneSugerencia.setBackground(new java.awt.Color(0, 102, 102));
        jTextPaneSugerencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPaneSugerencia.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPaneSugerencia.setViewportView(jTextPaneSugerencia);

        panelSugerencia.add(jScrollPaneSugerencia);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelPrincipal.add(panelSugerencia, gridBagConstraints);

        panelBoton.setBackground(new java.awt.Color(0, 78, 97));
        panelBoton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBoton.setForeground(new java.awt.Color(255, 255, 255));

        botonGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        panelBoton.add(botonGuardar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelPrincipal.add(panelBoton, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAcuerdo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcuerdo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAcuerdo4ActionPerformed

    private void radio1A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1A1ActionPerformed

    private void radio1A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1A2ActionPerformed

    private void radio1A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1A3ActionPerformed

    private void radio1A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1A4ActionPerformed

    private void radio1A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1A5ActionPerformed

    private void radio1A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1A6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1A6ActionPerformed

    private void radio1A7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1A7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1A7ActionPerformed

    private void radio1A8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1A8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1A8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncuestaEficaciaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncuestaEficaciaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncuestaEficaciaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncuestaEficaciaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EncuestaEficaciaVista dialog = new EncuestaEficaciaVista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAcuerdo1;
    private javax.swing.JButton botonAcuerdo2;
    private javax.swing.JButton botonAcuerdo3;
    private javax.swing.JButton botonAcuerdo4;
    private javax.swing.JButton botonAcuerdo5;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JScrollPane jScrollPaneSugerencia;
    private javax.swing.JTextPane jTextPaneSugerencia;
    private javax.swing.JLabel labelAfirmacion1;
    private javax.swing.JLabel labelAfirmacion2;
    private javax.swing.JLabel labelAfirmacion3;
    private javax.swing.JLabel labelAfirmacion4;
    private javax.swing.JLabel labelAfirmacion5;
    private javax.swing.JLabel labelAfirmacion6;
    private javax.swing.JLabel labelAfirmacion7;
    private javax.swing.JLabel labelAfirmacion8;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelInstrucciones;
    private javax.swing.JLabel labelRespuesta;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelAfirmacion1;
    private javax.swing.JPanel panelAfirmacion2;
    private javax.swing.JPanel panelAfirmacion3;
    private javax.swing.JPanel panelAfirmacion4;
    private javax.swing.JPanel panelAfirmacion5;
    private javax.swing.JPanel panelAfirmacion6;
    private javax.swing.JPanel panelAfirmacion7;
    private javax.swing.JPanel panelAfirmacion8;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelDatosCurso;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRespuesta1;
    private javax.swing.JPanel panelRespuesta2;
    private javax.swing.JPanel panelRespuesta3;
    private javax.swing.JPanel panelRespuesta4;
    private javax.swing.JPanel panelRespuesta5;
    private javax.swing.JPanel panelRespuesta6;
    private javax.swing.JPanel panelRespuesta7;
    private javax.swing.JPanel panelRespuesta8;
    private javax.swing.JPanel panelRespuestaAfirmacion1;
    private javax.swing.JPanel panelRespuestaAfirmacion2;
    private javax.swing.JPanel panelRespuestaAfirmacion3;
    private javax.swing.JPanel panelRespuestaAfirmacion4;
    private javax.swing.JPanel panelRespuestaAfirmacion5;
    private javax.swing.JPanel panelRespuestaAfirmacion6;
    private javax.swing.JPanel panelRespuestaAfirmacion7;
    private javax.swing.JPanel panelRespuestaAfirmacion8;
    private javax.swing.JPanel panelRespuestas;
    private javax.swing.JPanel panelSugerencia;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JRadioButton radio1A1;
    private javax.swing.JRadioButton radio1A2;
    private javax.swing.JRadioButton radio1A3;
    private javax.swing.JRadioButton radio1A4;
    private javax.swing.JRadioButton radio1A5;
    private javax.swing.JRadioButton radio1A6;
    private javax.swing.JRadioButton radio1A7;
    private javax.swing.JRadioButton radio1A8;
    private javax.swing.JRadioButton radio2A1;
    private javax.swing.JRadioButton radio2A2;
    private javax.swing.JRadioButton radio2A3;
    private javax.swing.JRadioButton radio2A4;
    private javax.swing.JRadioButton radio2A5;
    private javax.swing.JRadioButton radio2A6;
    private javax.swing.JRadioButton radio2A7;
    private javax.swing.JRadioButton radio2A8;
    private javax.swing.JRadioButton radio3A1;
    private javax.swing.JRadioButton radio3A2;
    private javax.swing.JRadioButton radio3A3;
    private javax.swing.JRadioButton radio3A4;
    private javax.swing.JRadioButton radio3A5;
    private javax.swing.JRadioButton radio3A6;
    private javax.swing.JRadioButton radio3A7;
    private javax.swing.JRadioButton radio3A8;
    private javax.swing.JRadioButton radio4A1;
    private javax.swing.JRadioButton radio4A2;
    private javax.swing.JRadioButton radio4A3;
    private javax.swing.JRadioButton radio4A4;
    private javax.swing.JRadioButton radio4A5;
    private javax.swing.JRadioButton radio4A6;
    private javax.swing.JRadioButton radio4A7;
    private javax.swing.JRadioButton radio4A8;
    private javax.swing.JRadioButton radio5A1;
    private javax.swing.JRadioButton radio5A2;
    private javax.swing.JRadioButton radio5A3;
    private javax.swing.JRadioButton radio5A4;
    private javax.swing.JRadioButton radio5A5;
    private javax.swing.JRadioButton radio5A6;
    private javax.swing.JRadioButton radio5A7;
    private javax.swing.JRadioButton radio5A8;
    // End of variables declaration//GEN-END:variables
}
